--DDL - CRIANDO BANCO DE DADOS


CREATE DATABASE HEALTH_CLINIC_KELLER

-- USANDO BANCO DE DADOS

USE HEALTH_CLINIC_KELLER


-- CRIANDO AS TABELAS 

CREATE TABLE TipoUsuario
(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	TituloTipoUsuario VARCHAR(50) NOT NULL,
)

CREATE TABLE Especialidade
(
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	TituloEspecialidade VARCHAR(50) NOT NULL,
)

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	NomeFantasia VARCHAR(50) NOT NULL,
	RazaoSocial VARCHAR(50) UNIQUE NOT NULL,
	CNPJ VARCHAR(14) UNIQUE NOT NULL,
	HorarioFuncionamento VARCHAR(50) NOT NULL,
	Endereco VARCHAR(70) NOT NULL
)


CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(50) NOT NULL UNIQUE,
	Senha VARCHAR(20) NOT NULL
)

CREATE TABLE Paciente
(
	IdPaciente INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	CPF CHAR(50) NOT NULL UNIQUE,	
)

CREATE TABLE Medico
(
	IdMedico INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade) NOT NULL,
	CRM VARCHAR(50) NOT NULL UNIQUE,
	
)

CREATE TABLE Consulta
(
	IdConsulta INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL,
	IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente) NOT NULL,
	IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico) NOT NULL,
	Data_ DATE NOT NULL,
	Hora TIME NOT NULL,
	Prontuario VARCHAR(200)
)









SELECT * FROM TipoUsuario
SELECT * FROM Especialidade
SELECT * FROM Clinica
SELECT * FROM Usuario
SELECT * FROM Paciente
SELECT * FROM Consulta
SELECT * FROM Medico